// SPDX-License-Identifier: Apache-2.0
import Foundation
import Testing

@Test func predecessorIdentityMatrixIsRetained() throws {
    let url = try #require(Bundle.module.url(forResource: "predecessor-identity-macos-arm64", withExtension: "txt", subdirectory: "Fixtures"))
    let baseline = try String(contentsOf: url, encoding: .utf8).split(separator: "\n").map(String.init)
        .filter { !$0.hasPrefix("AGGREGATE ") }
    let actual = identityHashRecords()
    #expect(baseline.count == 71)
    #expect(actual.count == baseline.count)
    #expect(!actual.contains { $0.contains("ERROR") })
    for (expected, observed) in zip(baseline, actual) {
        let name = expected.split(separator: " ")[0]
        #expect(observed.split(separator: " ").first == name)
        // SOF3 is integer-exact across platforms, including nonzero point
        // transforms and signed raw-bit legacy cases. This does not advertise
        // portable signed JPEG interpretation through the new public API.
        if name.contains("/lossless") || name.contains("/nearloss") {
            #expect(expected == observed, "Predecessor SOF3 identity changed: \(name)")
        }
        #if os(macOS) && canImport(Accelerate) && arch(arm64)
        // The frozen complete matrix was generated by the pinned predecessor
        // on macOS ARM64; floating-point DSP hashes are platform-specific.
        #expect(expected == observed, "Predecessor macOS ARM64 identity changed: \(name)")
        #endif
    }
}
